@startuml
skinparam linetype ortho
left to right direction
'top to bottom direction

class Graph {
    -adjacencyList: Map<Node, Set<Node>>
    +addEdge(Node, Node): void
    +getNeighbors(Node): Set<Node>
    +printGraph(): void
}

class Node {
    -id: int
    +Node(int): void
    +getId(): int
    +equals(Object): boolean
    +hashCode(): int
    +toString(): String
}

class GraphReader {
    +readGraph(String): List<List<Integer>>
}

class BFSParallel {
    -graph: Graph
    -startNode: Node
    -queue: ConcurrentLinkedQueue<Node>
    -visited: ConcurrentHashMap<Node, Boolean>
    +BFSParallel(Graph, Node): void
    +call(): Set<Node>
}

class DFSParallel {
    -graph: Graph
    -startNode: Node
    -stack: ConcurrentLinkedDeque<Node>
    -visited: ConcurrentHashMap<Node, Boolean>
    +DFSParallel(Graph, Node): void
    +call(): Set<Node>
}

class BFSTreeParallel {
    -root: TreeNode
    +BFSTreeParallel(TreeNode): void
    +call(): Set<TreeNode>
}

class DFSTreeParallel {
    -root: TreeNode
    +DFSTreeParallel(TreeNode): void
    +call(): Set<TreeNode>
}

class GraphAlgorithmExecutor {
    +runParallelMethods(String, int): void
    +runParallelBFS(ExecutorService, Graph, Node): Future<Set<Node>>
    +runParallelDFS(ExecutorService, Graph, Node): Future<Set<Node>>
}

class TreeAlgorithmExecutor {
    +runParallelMethods(String, int): void
    +monitorParallelMemoryUsage(Callable<Set<TreeNode>>): double
}

class ExcelDataRecorder {
    +writeData(String, List<Double>, List<Double>, int, boolean, boolean): void
    +writeHeader(Sheet, boolean): void
    +writeDataInColumns(List<Double>, List<Double>, int, Row): void
    +getNextEmptyRow(Sheet, int): int
}

class TreeNode {
    -value: int
    -children: ArrayList<TreeNode>
    +TreeNode(int): void
    +addChild(TreeNode): void
    +getValue(): int
    +getChildren(): ArrayList<TreeNode>
}

class Main {
    +main(String[]): void
}

Graph --> Node : contains
GraphReader ..> Graph : reads and converts to
BFSParallel --> Graph
BFSParallel --> Node
DFSParallel --> Graph
DFSParallel --> Node
BFSTreeParallel --> TreeNode
DFSTreeParallel --> TreeNode
GraphAlgorithmExecutor --> BFSParallel : uses
GraphAlgorithmExecutor --> DFSParallel : uses
TreeAlgorithmExecutor --> BFSTreeParallel : uses
TreeAlgorithmExecutor --> DFSTreeParallel : uses
Main ..> GraphAlgorithmExecutor : executes
Main ..> TreeAlgorithmExecutor : executes

@enduml
